# Leetcode 1545: Find Kth Bit in Nth Binary String
# https://leetcode.com/problems/find-kth-bit-in-nth-binary-string/
# Solved on 3rd of March, 2026
class Solution:
    def findKthBit(self, n: int, k: int) -> str:
        """
        Finds the kth bit in the nth binary string generated by a specific recursive rule.

        :param n: The index of the binary string to generate.
        :param k: The 1-indexed position of the bit to find.
        :return: The kth bit as a string ('0' or '1').
        """
        invertCount = 0
        stringLength = (1 << n) - 1

        while k > 1:
            midPoint = stringLength // 2 + 1

            if k == midPoint:
                return str(1 - (invertCount % 2))

            if k > midPoint:
                k = stringLength - k + 1
                invertCount += 1

            stringLength //= 2

        return str(invertCount % 2)