# Leetcode 3304: Find the K-th Character in String Game I
# https://leetcode.com/problems/find-the-k-th-character-in-the-string-game-i/
# Solved on 3rd of July, 2025
class Solution:
    def kthCharacter(self, k: int) -> str:
        """
        Finds the k-th character in a sequence generated by a specific pattern.
        The pattern starts with 'a', and each subsequent string is formed by
        concatenating the previous string, then the next character in the alphabet,
        then the previous string again.
        """
        lengths = [1]
        while lengths[-1] < k:
            lengths.append(lengths[-1] * 2)

        n = len(lengths) - 1
        shift_count = 0

        while n > 0:
            if k > lengths[n - 1]:
                k -= lengths[n - 1]
                shift_count = (shift_count + 1) % 26
            n -= 1

        return chr((ord('a') - ord('a') + shift_count) % 26 + ord('a'))